-- =============================================================================
-- COMBINED MIGRATIONS — all 10 migration files concatenated in order.
-- =============================================================================
-- Purpose: mobile-friendly single-paste copy of the entire schema. Each of
-- the individual files under supabase/migrations/ is idempotent, so running
-- this combined file on a fresh project (or even on one that's partially
-- migrated) is safe — every `create ... if not exists`, `add column if not
-- exists`, and `exception when duplicate_object` guard still applies.
--
-- Paste this whole file into the Supabase SQL editor once and hit Run.
--
-- NOTE: Always treat the per-migration files (0001_init.sql → 0010_...sql)
-- as the source of truth. Do not edit this file by hand — regenerate it
-- when a new migration is added.
-- -----------------------------------------------------------------------------


-- #############################################################################
-- 0001_init.sql
-- #############################################################################

-- =============================================================================
-- Coaching platform — initial schema (Phase 1)
-- =============================================================================
-- Conventions:
--   * UUID primary keys generated with gen_random_uuid()
--   * timestamptz for all timestamps; updated_at maintained via trigger
--   * "profiles" extends auth.users (Supabase native auth) with role + name
--   * "clients" holds coaching-specific personal info per client user
-- -----------------------------------------------------------------------------

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.user_role as enum ('admin', 'client');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.experience_level as enum ('beginner', 'intermediate', 'advanced');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.training_goal as enum (
    'fat_loss', 'muscle_gain', 'recomposition', 'athletic_performance'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.nutrition_mode as enum ('fixed', 'flexible');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.workout_done_status as enum ('yes', 'partial', 'no');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles  (1:1 with auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id                uuid primary key references auth.users(id) on delete cascade,
  email             text not null unique,
  role              public.user_role not null default 'client',
  full_name         text,
  preferred_locale  text not null default 'en',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create a profile row when a new auth.users row is inserted.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role, full_name)
  values (
    new.id,
    new.email,
    coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'client'),
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- clients  (coaching-specific personal info)
-- ---------------------------------------------------------------------------
create table if not exists public.clients (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null unique references public.profiles(id) on delete cascade,
  age                 int,
  height_cm           numeric(5,1),
  starting_weight_kg  numeric(5,2),
  experience_level    public.experience_level,
  goal                public.training_goal,
  health_notes        text,
  start_date          date,
  target_date         date,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

drop trigger if exists trg_clients_updated_at on public.clients;
create trigger trg_clients_updated_at
  before update on public.clients
  for each row execute function public.set_updated_at();

create index if not exists idx_clients_user_id on public.clients(user_id);

-- ---------------------------------------------------------------------------
-- Workout plans
-- ---------------------------------------------------------------------------
create table if not exists public.workout_plans (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients(id) on delete cascade,
  name        text not null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists idx_workout_plans_client on public.workout_plans(client_id);
drop trigger if exists trg_workout_plans_updated_at on public.workout_plans;
create trigger trg_workout_plans_updated_at
  before update on public.workout_plans
  for each row execute function public.set_updated_at();

create table if not exists public.workout_days (
  id          uuid primary key default gen_random_uuid(),
  plan_id     uuid not null references public.workout_plans(id) on delete cascade,
  day_number  int not null,
  day_name    text not null,
  unique (plan_id, day_number)
);
create index if not exists idx_workout_days_plan on public.workout_days(plan_id);

create table if not exists public.exercises (
  id            uuid primary key default gen_random_uuid(),
  day_id        uuid not null references public.workout_days(id) on delete cascade,
  name          text not null,
  sets          int not null,
  reps          text not null,            -- "8-12" or "10" — kept as text for ranges
  rest_seconds  int not null default 90,
  notes         text,
  video_url     text,
  display_order int not null default 0,
  created_at    timestamptz not null default now()
);
create index if not exists idx_exercises_day on public.exercises(day_id);

-- Logged set performance per workout
create table if not exists public.workout_logs (
  id            uuid primary key default gen_random_uuid(),
  client_id     uuid not null references public.clients(id) on delete cascade,
  exercise_id   uuid not null references public.exercises(id) on delete cascade,
  log_date      date not null default current_date,
  set_number    int not null,
  weight_kg     numeric(6,2),
  reps_done     int,
  created_at    timestamptz not null default now()
);
create index if not exists idx_workout_logs_client_date
  on public.workout_logs(client_id, log_date);

-- ---------------------------------------------------------------------------
-- Nutrition
-- ---------------------------------------------------------------------------
create table if not exists public.nutrition_plans (
  id              uuid primary key default gen_random_uuid(),
  client_id       uuid not null references public.clients(id) on delete cascade,
  mode            public.nutrition_mode not null default 'flexible',
  calories_target int,
  protein_target  int,
  carbs_target    int,
  fat_target      int,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_nutrition_plans_client on public.nutrition_plans(client_id);
drop trigger if exists trg_nutrition_plans_updated_at on public.nutrition_plans;
create trigger trg_nutrition_plans_updated_at
  before update on public.nutrition_plans
  for each row execute function public.set_updated_at();

-- Fixed-mode meals (food_items stored as JSON array of {name, grams, kcal, p, c, f})
create table if not exists public.meals (
  id          uuid primary key default gen_random_uuid(),
  plan_id     uuid not null references public.nutrition_plans(id) on delete cascade,
  meal_type   text not null,            -- breakfast | lunch | dinner | snack | etc.
  food_items  jsonb not null default '[]'::jsonb,
  display_order int not null default 0
);
create index if not exists idx_meals_plan on public.meals(plan_id);

-- Shared food database used by flexible-mode logging
create table if not exists public.food_database (
  id                    uuid primary key default gen_random_uuid(),
  name                  text not null unique,
  name_ar               text,
  calories_per_100g     numeric(6,2) not null,
  protein_per_100g      numeric(6,2) not null,
  carbs_per_100g        numeric(6,2) not null,
  fat_per_100g          numeric(6,2) not null,
  is_custom             boolean not null default false,
  created_by            uuid references public.profiles(id) on delete set null,
  created_at            timestamptz not null default now()
);

-- Per-day flexible-mode food logging
create table if not exists public.food_logs (
  id                  uuid primary key default gen_random_uuid(),
  client_id           uuid not null references public.clients(id) on delete cascade,
  food_id             uuid not null references public.food_database(id) on delete restrict,
  log_date            date not null default current_date,
  weight_grams        numeric(7,1) not null,
  calculated_calories numeric(7,2) not null,
  calculated_protein  numeric(6,2) not null,
  calculated_carbs    numeric(6,2) not null,
  calculated_fat      numeric(6,2) not null,
  meal_type           text,
  created_at          timestamptz not null default now()
);
create index if not exists idx_food_logs_client_date
  on public.food_logs(client_id, log_date);

-- ---------------------------------------------------------------------------
-- Body tracking
-- ---------------------------------------------------------------------------
create table if not exists public.body_measurements (
  id                  uuid primary key default gen_random_uuid(),
  client_id           uuid not null references public.clients(id) on delete cascade,
  measured_on         date not null default current_date,
  weight_kg           numeric(5,2),
  waist_cm            numeric(5,2),
  chest_cm            numeric(5,2),
  shoulders_cm        numeric(5,2),
  hips_cm             numeric(5,2),
  left_arm_cm         numeric(5,2),
  right_arm_cm        numeric(5,2),
  left_thigh_cm       numeric(5,2),
  right_thigh_cm      numeric(5,2),
  body_fat_percent    numeric(4,1),
  created_at          timestamptz not null default now(),
  unique (client_id, measured_on)
);
create index if not exists idx_body_measurements_client
  on public.body_measurements(client_id, measured_on desc);

create table if not exists public.weight_logs (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients(id) on delete cascade,
  log_date    date not null default current_date,
  weight_kg   numeric(5,2) not null,
  created_at  timestamptz not null default now(),
  unique (client_id, log_date)
);
create index if not exists idx_weight_logs_client
  on public.weight_logs(client_id, log_date desc);

create table if not exists public.progress_photos (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients(id) on delete cascade,
  taken_on    date not null default current_date,
  storage_path text not null,           -- path inside the "progress-photos" storage bucket
  note        text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_progress_photos_client
  on public.progress_photos(client_id, taken_on desc);

-- ---------------------------------------------------------------------------
-- Daily check-in / compliance self-rating
-- ---------------------------------------------------------------------------
create table if not exists public.daily_checkins (
  id                  uuid primary key default gen_random_uuid(),
  client_id           uuid not null references public.clients(id) on delete cascade,
  checkin_date        date not null default current_date,
  workout_done        public.workout_done_status not null,
  workout_sets_done   int,
  diet_compliance     int,                 -- 0..100
  cardio_done         boolean not null default false,
  cardio_minutes      int,
  sleep_quality       int,                 -- 1..5
  sleep_hours         numeric(3,1),
  client_note         text,
  created_at          timestamptz not null default now(),
  unique (client_id, checkin_date),
  constraint diet_compliance_range
    check (diet_compliance is null or diet_compliance between 0 and 100),
  constraint sleep_quality_range
    check (sleep_quality is null or sleep_quality between 1 and 5)
);
create index if not exists idx_daily_checkins_client
  on public.daily_checkins(client_id, checkin_date desc);

-- ---------------------------------------------------------------------------
-- Site content (landing page CMS)
-- ---------------------------------------------------------------------------
create table if not exists public.site_content (
  id            uuid primary key default gen_random_uuid(),
  section_key   text not null unique,
  content_json  jsonb not null default '{}'::jsonb,
  is_published  boolean not null default true,
  updated_at    timestamptz not null default now()
);
drop trigger if exists trg_site_content_updated_at on public.site_content;
create trigger trg_site_content_updated_at
  before update on public.site_content
  for each row execute function public.set_updated_at();


-- #############################################################################
-- 0002_rls.sql
-- #############################################################################

-- =============================================================================
-- Row-Level Security policies
-- =============================================================================

-- helper: is current user an admin?
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- helper: client_id owned by the current auth user
create or replace function public.current_client_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from public.clients where user_id = auth.uid();
$$;

alter table public.profiles enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read
  on public.profiles for select
  using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update
  on public.profiles for update
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_insert on public.profiles;
create policy profiles_admin_insert
  on public.profiles for insert
  with check (public.is_admin());

alter table public.clients enable row level security;

drop policy if exists clients_self_read on public.clients;
create policy clients_self_read
  on public.clients for select
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists clients_admin_write on public.clients;
create policy clients_admin_write
  on public.clients for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists clients_self_update on public.clients;
create policy clients_self_update
  on public.clients for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

alter table public.workout_plans enable row level security;
alter table public.workout_days enable row level security;
alter table public.exercises enable row level security;

drop policy if exists workout_plans_read on public.workout_plans;
create policy workout_plans_read on public.workout_plans for select
  using (
    public.is_admin()
    or client_id = public.current_client_id()
  );

drop policy if exists workout_plans_admin_write on public.workout_plans;
create policy workout_plans_admin_write on public.workout_plans for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists workout_days_read on public.workout_days;
create policy workout_days_read on public.workout_days for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.workout_plans p
      where p.id = workout_days.plan_id
        and p.client_id = public.current_client_id()
    )
  );

drop policy if exists workout_days_admin_write on public.workout_days;
create policy workout_days_admin_write on public.workout_days for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists exercises_read on public.exercises;
create policy exercises_read on public.exercises for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.workout_days d
      join public.workout_plans p on p.id = d.plan_id
      where d.id = exercises.day_id
        and p.client_id = public.current_client_id()
    )
  );

drop policy if exists exercises_admin_write on public.exercises;
create policy exercises_admin_write on public.exercises for all
  using (public.is_admin()) with check (public.is_admin());

alter table public.workout_logs enable row level security;

drop policy if exists workout_logs_owner on public.workout_logs;
create policy workout_logs_owner on public.workout_logs for all
  using (client_id = public.current_client_id() or public.is_admin())
  with check (client_id = public.current_client_id() or public.is_admin());

alter table public.nutrition_plans enable row level security;
alter table public.meals enable row level security;

drop policy if exists nutrition_plans_read on public.nutrition_plans;
create policy nutrition_plans_read on public.nutrition_plans for select
  using (public.is_admin() or client_id = public.current_client_id());

drop policy if exists nutrition_plans_admin_write on public.nutrition_plans;
create policy nutrition_plans_admin_write on public.nutrition_plans for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists meals_read on public.meals;
create policy meals_read on public.meals for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.nutrition_plans np
      where np.id = meals.plan_id
        and np.client_id = public.current_client_id()
    )
  );

drop policy if exists meals_admin_write on public.meals;
create policy meals_admin_write on public.meals for all
  using (public.is_admin()) with check (public.is_admin());

alter table public.food_database enable row level security;

drop policy if exists food_db_read_all on public.food_database;
create policy food_db_read_all on public.food_database for select using (true);

drop policy if exists food_db_admin_write on public.food_database;
create policy food_db_admin_write on public.food_database for all
  using (public.is_admin()) with check (public.is_admin());

alter table public.food_logs enable row level security;
alter table public.body_measurements enable row level security;
alter table public.weight_logs enable row level security;
alter table public.progress_photos enable row level security;
alter table public.daily_checkins enable row level security;

create or replace function public.assert_owner_or_admin(target_client uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select target_client = public.current_client_id() or public.is_admin();
$$;

drop policy if exists food_logs_owner on public.food_logs;
create policy food_logs_owner on public.food_logs for all
  using (public.assert_owner_or_admin(client_id))
  with check (public.assert_owner_or_admin(client_id));

drop policy if exists body_measurements_owner on public.body_measurements;
create policy body_measurements_owner on public.body_measurements for all
  using (public.assert_owner_or_admin(client_id))
  with check (public.assert_owner_or_admin(client_id));

drop policy if exists weight_logs_owner on public.weight_logs;
create policy weight_logs_owner on public.weight_logs for all
  using (public.assert_owner_or_admin(client_id))
  with check (public.assert_owner_or_admin(client_id));

drop policy if exists progress_photos_owner on public.progress_photos;
create policy progress_photos_owner on public.progress_photos for all
  using (public.assert_owner_or_admin(client_id))
  with check (public.assert_owner_or_admin(client_id));

drop policy if exists daily_checkins_owner on public.daily_checkins;
create policy daily_checkins_owner on public.daily_checkins for all
  using (public.assert_owner_or_admin(client_id))
  with check (public.assert_owner_or_admin(client_id));

alter table public.site_content enable row level security;

drop policy if exists site_content_public_read on public.site_content;
create policy site_content_public_read
  on public.site_content for select
  using (is_published = true or public.is_admin());

drop policy if exists site_content_admin_write on public.site_content;
create policy site_content_admin_write
  on public.site_content for all
  using (public.is_admin()) with check (public.is_admin());


-- #############################################################################
-- 0003_seed_food_db.sql
-- #############################################################################

insert into public.food_database (name, name_ar, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g)
values
  ('Egg (whole)',          'بيض كامل',           155,  13.0,  1.1, 11.0),
  ('Egg white',            'بياض البيض',          52,  10.9,  0.7,  0.2),
  ('Chicken breast (raw)', 'صدر دجاج',           120,  23.0,  0.0,  2.6),
  ('Beef mince 90/10',     'لحم مفروم 90/10',    176,  20.0,  0.0, 10.0),
  ('Salmon fillet',        'سلمون',              208,  20.4,  0.0, 13.4),
  ('White rice (cooked)',  'أرز أبيض مطبوخ',     130,   2.7, 28.2,  0.3),
  ('Brown rice (cooked)',  'أرز بني مطبوخ',      112,   2.6, 23.5,  0.9),
  ('Oats (dry)',           'شوفان',              389,  16.9, 66.3,  6.9),
  ('Sweet potato (raw)',   'بطاطا حلوة',          86,   1.6, 20.1,  0.1),
  ('Potato (raw)',         'بطاطس',               77,   2.0, 17.5,  0.1),
  ('Banana',               'موز',                 89,   1.1, 22.8,  0.3),
  ('Apple',                'تفاح',                52,   0.3, 13.8,  0.2),
  ('Almonds',              'لوز',                579,  21.2, 21.7, 49.9),
  ('Olive oil',            'زيت زيتون',          884,   0.0,  0.0,100.0),
  ('Greek yogurt 2%',      'زبادي يوناني',        73,  10.0,  3.6,  1.9),
  ('Milk 2%',              'حليب 2٪',             50,   3.3,  4.9,  2.0),
  ('Tuna in water',        'تونة بالماء',        116,  25.5,  0.0,  0.8),
  ('Whey protein (scoop)', 'بروتين واي',         400,  80.0,  8.0,  6.0),
  ('Cheese, white',        'جبن أبيض',           264,  18.0,  2.0, 21.0),
  ('Bread, whole wheat',   'خبز قمح كامل',       247,  13.0, 41.0,  4.2),
  ('Hummus',               'حمص',                166,   7.9, 14.3,  9.6),
  ('Foul (cooked)',        'فول مدمس',           130,   8.5, 19.5,  3.0)
on conflict (name) do nothing;


-- #############################################################################
-- 0004_seed_site_content.sql
-- #############################################################################

insert into public.site_content (section_key, content_json, is_published)
values
  ('hero', jsonb_build_object(
    'headline_en', 'Build the body you actually want.',
    'headline_ar', 'ابني الجسم اللي إنت عايزه فعلاً.',
    'subheadline_en', 'Personalized coaching, smart nutrition, and daily accountability — all in one place.',
    'subheadline_ar', 'كوتشينج شخصي، تغذية ذكية، ومتابعة يومية — كل ده في مكان واحد.',
    'cta_text_en', 'Start your journey',
    'cta_text_ar', 'ابدأ رحلتك',
    'background_url', ''
  ), true),
  ('features', jsonb_build_object(
    'items', jsonb_build_array(
      jsonb_build_object(
        'icon', 'Dumbbell',
        'title_en', 'Personalized Workout Plan',
        'title_ar', 'خطة تمرين مخصصة',
        'desc_en', 'Programs built around your level, schedule, and goals.',
        'desc_ar', 'برامج مصممة حسب مستواك وجدولك وأهدافك.'
      ),
      jsonb_build_object(
        'icon', 'Apple',
        'title_en', 'Flexible Nutrition System',
        'title_ar', 'نظام تغذية مرن',
        'desc_en', 'Hit your macros without giving up the foods you love.',
        'desc_ar', 'وصّل أهدافك من غير ما تتنازل عن الأكل اللي بتحبه.'
      ),
      jsonb_build_object(
        'icon', 'Activity',
        'title_en', 'Daily Check-in & Tracking',
        'title_ar', 'متابعة يومية',
        'desc_en', 'Stay accountable with quick nightly check-ins.',
        'desc_ar', 'اتابع نفسك يومياً بفورم سريع كل ليلة.'
      ),
      jsonb_build_object(
        'icon', 'MessageCircle',
        'title_en', 'Direct Coach Access',
        'title_ar', 'تواصل مباشر مع الكوتش',
        'desc_en', 'Real feedback from a real coach — not a chatbot.',
        'desc_ar', 'فيدباك حقيقي من كوتش حقيقي — مش بوت.'
      ),
      jsonb_build_object(
        'icon', 'Camera',
        'title_en', 'Visual & Metric Progress',
        'title_ar', 'تتبع التقدم بالصور والأرقام',
        'desc_en', 'Track weight, measurements, and progress photos in one place.',
        'desc_ar', 'تابع وزنك ومقاساتك وصور التقدم في مكان واحد.'
      )
    )
  ), true),
  ('how_it_works', jsonb_build_object(
    'steps', jsonb_build_array(
      jsonb_build_object('title_en', 'Join', 'title_ar', 'سجّل', 'desc_en', 'Sign up and share your goals.', 'desc_ar', 'سجّل وقولنا هدفك.'),
      jsonb_build_object('title_en', 'Get Your Plan', 'title_ar', 'استلم برنامجك', 'desc_en', 'Receive a custom workout + nutrition plan.', 'desc_ar', 'هتستلم برنامج تمرين وتغذية مخصص ليك.'),
      jsonb_build_object('title_en', 'Track & Transform', 'title_ar', 'تابع واتغير', 'desc_en', 'Log workouts and check in daily — we adjust as you go.', 'desc_ar', 'سجّل تمرينك وعمل تشيك-إن يومي — احنا بنعدل معاك.')
    )
  ), true),
  ('testimonials', jsonb_build_object(
    'is_visible', true,
    'items', jsonb_build_array()
  ), true),
  ('pricing', jsonb_build_object(
    'is_visible', false,
    'tiers', jsonb_build_array()
  ), true),
  ('cta_footer', jsonb_build_object(
    'headline_en', 'Ready to start?',
    'headline_ar', 'جاهز تبدأ؟',
    'cta_text_en', 'Sign up now',
    'cta_text_ar', 'سجّل دلوقتي'
  ), true),
  ('theme', jsonb_build_object(
    'primary', '#a3e635',
    'accent', '#f97316',
    'background', '#0f0f0f'
  ), true)
on conflict (section_key) do nothing;


-- #############################################################################
-- 0005_progress_photos_storage.sql
-- #############################################################################

insert into storage.buckets (id, name, public)
values ('progress-photos', 'progress-photos', false)
on conflict (id) do nothing;

create or replace function public.storage_path_client_id(path text)
returns uuid
language sql
immutable
as $$
  select (split_part(path, '/', 1))::uuid;
$$;

drop policy if exists progress_photos_select on storage.objects;
create policy progress_photos_select
  on storage.objects for select
  using (
    bucket_id = 'progress-photos'
    and (
      public.is_admin()
      or public.current_client_id() = public.storage_path_client_id(name)
    )
  );

drop policy if exists progress_photos_insert on storage.objects;
create policy progress_photos_insert
  on storage.objects for insert
  with check (
    bucket_id = 'progress-photos'
    and (
      public.is_admin()
      or public.current_client_id() = public.storage_path_client_id(name)
    )
  );

drop policy if exists progress_photos_delete on storage.objects;
create policy progress_photos_delete
  on storage.objects for delete
  using (
    bucket_id = 'progress-photos'
    and (
      public.is_admin()
      or public.current_client_id() = public.storage_path_client_id(name)
    )
  );


-- #############################################################################
-- 0006_workout_plan_coach_notes.sql
-- #############################################################################

alter table public.workout_plans
  add column if not exists general_notes text,
  add column if not exists attention_notes text;


-- #############################################################################
-- 0007_client_admin_metadata.sql
-- #############################################################################

alter table public.clients
  add column if not exists phone              text,
  add column if not exists whatsapp_phone     text,
  add column if not exists coach_notes        text,
  add column if not exists is_archived        boolean not null default false;

create index if not exists idx_clients_archived
  on public.clients(is_archived);


-- #############################################################################
-- 0008_messages.sql
-- #############################################################################

create table if not exists public.messages (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients(id) on delete cascade,
  sender_id   uuid not null references public.profiles(id) on delete cascade,
  body        text not null check (length(body) between 1 and 4000),
  created_at  timestamptz not null default now(),
  read_at     timestamptz
);

create index if not exists idx_messages_client_created
  on public.messages (client_id, created_at);
create index if not exists idx_messages_unread
  on public.messages (client_id) where read_at is null;
create index if not exists idx_messages_sender
  on public.messages (sender_id);

alter table public.messages enable row level security;

drop policy if exists "messages_read" on public.messages;
create policy "messages_read"
  on public.messages
  for select
  to authenticated
  using (
    exists (
      select 1 from public.clients c
      where c.id = messages.client_id
        and c.user_id = auth.uid()
    )
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

drop policy if exists "messages_insert" on public.messages;
create policy "messages_insert"
  on public.messages
  for insert
  to authenticated
  with check (
    sender_id = auth.uid()
    and (
      exists (
        select 1 from public.clients c
        where c.id = messages.client_id
          and c.user_id = auth.uid()
      )
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
      )
    )
  );

drop policy if exists "messages_update_read" on public.messages;
create policy "messages_update_read"
  on public.messages
  for update
  to authenticated
  using (
    sender_id <> auth.uid()
    and (
      exists (
        select 1 from public.clients c
        where c.id = messages.client_id
          and c.user_id = auth.uid()
      )
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
      )
    )
  )
  with check (
    sender_id <> auth.uid()
    and (
      exists (
        select 1 from public.clients c
        where c.id = messages.client_id
          and c.user_id = auth.uid()
      )
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
      )
    )
  );

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then
    execute 'alter publication supabase_realtime add table public.messages';
  end if;
exception when undefined_object then
  null;
end $$;


-- #############################################################################
-- 0009_packages_and_applications.sql
-- #############################################################################

do $$ begin
  create type public.billing_period as enum (
    'monthly', 'quarterly', 'biannual', 'yearly', 'one_time'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.application_status as enum (
    'new', 'contacted', 'in_review', 'accepted', 'rejected', 'archived'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.activity_level as enum (
    'sedentary', 'light', 'moderate', 'active', 'very_active'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.training_location as enum ('home', 'gym', 'both');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.contact_method as enum ('whatsapp', 'phone', 'email');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.gender as enum ('male', 'female', 'other');
exception when duplicate_object then null; end $$;

create table if not exists public.packages (
  id              uuid primary key default gen_random_uuid(),
  slug            text not null unique,
  name_en         text not null,
  name_ar         text not null,
  description_en  text not null default '',
  description_ar  text not null default '',
  price           numeric(10, 2) not null default 0,
  currency        text not null default 'USD',
  billing_period  public.billing_period not null default 'monthly',
  features_en     text[] not null default '{}'::text[],
  features_ar     text[] not null default '{}'::text[],
  cta_label_en    text,
  cta_label_ar    text,
  is_featured     boolean not null default false,
  is_active       boolean not null default true,
  display_order   int not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists trg_packages_updated_at on public.packages;
create trigger trg_packages_updated_at
  before update on public.packages
  for each row execute function public.set_updated_at();

create index if not exists idx_packages_active_order
  on public.packages(is_active, display_order);

create table if not exists public.coaching_applications (
  id                       uuid primary key default gen_random_uuid(),
  full_name                text not null,
  email                    text not null,
  phone                    text not null,
  country                  text,
  city                     text,
  preferred_contact        public.contact_method not null default 'whatsapp',
  best_contact_time        text,
  age                      int,
  gender                   public.gender,
  height_cm                numeric(5, 1),
  weight_kg                numeric(5, 2),
  body_fat_percent         numeric(4, 1),
  goal                     public.training_goal,
  target_weight_kg         numeric(5, 2),
  target_date              date,
  motivation_text          text,
  experience_level         public.experience_level,
  previous_coaching        boolean not null default false,
  previous_results_text    text,
  training_days_per_week   int,
  training_location        public.training_location,
  available_equipment_text text,
  preferred_training_time  text,
  injuries_or_conditions   text,
  medications              text,
  allergies                text,
  surgeries_text           text,
  dietary_restrictions     text,
  foods_disliked           text,
  current_diet_summary     text,
  water_intake_liters      numeric(4, 1),
  occupation               text,
  daily_activity_level     public.activity_level,
  sleep_hours_avg          numeric(3, 1),
  stress_level             int,
  smokes                   boolean not null default false,
  package_id               uuid references public.packages(id) on delete set null,
  notes                    text,
  locale                   text not null default 'en',
  status                   public.application_status not null default 'new',
  admin_notes              text,
  contacted_at             timestamptz,
  converted_client_id      uuid references public.clients(id) on delete set null,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  constraint stress_level_range
    check (stress_level is null or stress_level between 1 and 5),
  constraint training_days_range
    check (training_days_per_week is null or training_days_per_week between 0 and 14)
);

drop trigger if exists trg_coaching_applications_updated_at on public.coaching_applications;
create trigger trg_coaching_applications_updated_at
  before update on public.coaching_applications
  for each row execute function public.set_updated_at();

create index if not exists idx_coaching_applications_status_created
  on public.coaching_applications(status, created_at desc);

create index if not exists idx_coaching_applications_package
  on public.coaching_applications(package_id);

alter table public.packages enable row level security;

drop policy if exists packages_public_read on public.packages;
create policy packages_public_read
  on public.packages for select
  using (is_active = true or public.is_admin());

drop policy if exists packages_admin_write on public.packages;
create policy packages_admin_write
  on public.packages for all
  using (public.is_admin())
  with check (public.is_admin());

alter table public.coaching_applications enable row level security;

drop policy if exists coaching_applications_anon_insert on public.coaching_applications;
create policy coaching_applications_anon_insert
  on public.coaching_applications for insert
  with check (
    status = 'new'
    and admin_notes is null
    and contacted_at is null
    and converted_client_id is null
  );

drop policy if exists coaching_applications_admin_read on public.coaching_applications;
create policy coaching_applications_admin_read
  on public.coaching_applications for select
  using (public.is_admin());

drop policy if exists coaching_applications_admin_update on public.coaching_applications;
create policy coaching_applications_admin_update
  on public.coaching_applications for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists coaching_applications_admin_delete on public.coaching_applications;
create policy coaching_applications_admin_delete
  on public.coaching_applications for delete
  using (public.is_admin());


-- #############################################################################
-- 0010_payments_and_subscriptions.sql
-- #############################################################################

do $$ begin
  create type public.payment_status as enum (
    'pending', 'confirmed', 'rejected', 'refunded'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_method as enum (
    'vodafone_cash', 'instapay', 'bank_transfer', 'cash', 'other'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.subscription_status as enum (
    'none', 'trialing', 'active', 'expiring_soon', 'expired', 'suspended'
  );
exception when duplicate_object then null; end $$;

alter table public.clients
  add column if not exists subscription_status        public.subscription_status not null default 'none',
  add column if not exists subscription_starts_at     date,
  add column if not exists subscription_ends_at       date,
  add column if not exists last_payment_at            timestamptz,
  add column if not exists last_payment_id            uuid;

create index if not exists idx_clients_subscription_ends_at
  on public.clients(subscription_ends_at);
create index if not exists idx_clients_subscription_status
  on public.clients(subscription_status);

create table if not exists public.payments (
  id                 uuid primary key default gen_random_uuid(),
  client_id          uuid references public.clients(id) on delete set null,
  application_id     uuid references public.coaching_applications(id) on delete set null,
  package_id         uuid references public.packages(id) on delete set null,
  amount             numeric(10, 2) not null,
  currency           text not null default 'EGP',
  method             public.payment_method not null default 'vodafone_cash',
  reference_number   text,
  sender_phone       text,
  receipt_url        text,
  period_start       date,
  period_end         date,
  duration_days      int,
  status             public.payment_status not null default 'pending',
  paid_at            timestamptz,
  confirmed_at       timestamptz,
  confirmed_by       uuid references public.profiles(id) on delete set null,
  notes              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint payments_target_present
    check (client_id is not null or application_id is not null),
  constraint payments_amount_positive
    check (amount >= 0),
  constraint payments_duration_positive
    check (duration_days is null or duration_days > 0),
  constraint payments_period_consistent
    check (
      (period_start is null and period_end is null)
      or (period_start is not null and period_end is not null and period_end >= period_start)
    )
);

do $$ begin
  alter table public.clients
    add constraint clients_last_payment_fk
    foreign key (last_payment_id) references public.payments(id) on delete set null;
exception when duplicate_object then null; end $$;

drop trigger if exists trg_payments_updated_at on public.payments;
create trigger trg_payments_updated_at
  before update on public.payments
  for each row execute function public.set_updated_at();

create index if not exists idx_payments_client_created
  on public.payments(client_id, created_at desc);
create index if not exists idx_payments_application_created
  on public.payments(application_id, created_at desc);
create index if not exists idx_payments_status_created
  on public.payments(status, created_at desc);

create or replace function public.recompute_client_subscription(
  target_client uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  latest record;
  new_status public.subscription_status;
  today date := current_date;
begin
  select p.id, p.paid_at, p.period_start, p.period_end
    into latest
    from public.payments p
   where p.client_id = target_client
     and p.status = 'confirmed'
   order by coalesce(p.period_end, current_date) desc,
            coalesce(p.confirmed_at, p.created_at) desc
   limit 1;

  if latest.id is null then
    update public.clients
       set subscription_status     = 'none',
           subscription_starts_at  = null,
           subscription_ends_at    = null,
           last_payment_at         = null,
           last_payment_id         = null
     where id = target_client;
    return;
  end if;

  if latest.period_end is null then
    new_status := 'active';
  elsif latest.period_end < today then
    new_status := 'expired';
  elsif latest.period_end <= today + 7 then
    new_status := 'expiring_soon';
  else
    new_status := 'active';
  end if;

  update public.clients
     set subscription_status    = new_status,
         subscription_starts_at = coalesce(latest.period_start, subscription_starts_at),
         subscription_ends_at   = latest.period_end,
         last_payment_at        = latest.paid_at,
         last_payment_id        = latest.id
   where id = target_client;
end;
$$;

alter table public.payments enable row level security;

drop policy if exists payments_admin_all on public.payments;
create policy payments_admin_all
  on public.payments for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists payments_client_read_own on public.payments;
create policy payments_client_read_own
  on public.payments for select
  using (
    public.is_admin()
    or (client_id is not null and client_id = public.current_client_id())
  );

-- =============================================================================
-- END OF COMBINED MIGRATIONS
-- =============================================================================
